all: thread-object-destruction
thread-object-destruction: thread-object-destruction.cpp
	g++ -o thread-object-destruction -std=c++11 -g thread-object-destruction.cpp -pthread
clean:
	rm thread-object-destruction
