branches:
  only:
    - master
sudo: required
dist: trusty
language: cpp
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libglew-dev libglfw-dev libglm-dev libboost-dev libboost-dev libboost-system-dev libboost-filesystem-dev libmagick++-dev libxrandr-dev

addons:
  apt:
    sources:
        #- ubuntu-toolchain-r-test
    - debian-sid
    packages:
    - libglew-dev
    - libglfw-dev
    - libglm-dev
    - libboost-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libmagick++-dev

script: cd src && make
#script: ./travis-script.sh && mkdir build && cd build && cmake .. && make


#include:
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-4.9
#      env: COMPILER=g++-4.9
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#      env: COMPILER=g++-5
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#          packages:
#            - clang-3.6
#      env: COMPILER=clang++-3.6
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#          packages:
#            - clang-3.7
#      env: COMPILER=clang++-3.7
